services:
  traefik:
    image: traefik:2.8
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik.yml:/traefik.yml:ro'
      - './acme.json:/acme.json'
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.traefik.service=traefik'
      - 'traefik.http.routers.traefik.service=api@internal'

  database:
    image: mysql:8.3.0
    container_name: database
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql

  payment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: questionnaire
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3334:3334
    depends_on:
      - database
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.port=80'
      - 'traefik.http.routers.questionnaire.tls=true'
      - 'traefik.http.routers.questionnaire.rule=Host(`trainings.admin.asuta.or.tz`)'
      - 'traefik.http.routers.payment.entrypoints=websecure'
      - 'traefik.http.routers.payment.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.payment.service=payment'
      - 'traefik.http.services.payment.loadbalancer.server.port=3334'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.port=80'
      - 'traefik.http.routers.pma.tls=true'
      - 'traefik.http.routers.pma.rule=Host(`trainingspma.admin.asuta.or.tz`)'
      - 'traefik.http.routers.pma.entrypoints=websecure'
      - 'traefik.http.routers.pma.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.pma.service=pma'
      - 'traefik.http.services.pma.loadbalancer.server.port=80'

networks:
  proxy:
    external: true

volumes:
  paymentservicepg:
