services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./app.db
    restart: unless-stopped
    # Uncomment the following lines if you need a separate database
    # depends_on:
    #   - database
  
  # Uncomment if you want to add a database service
  # database:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=formdb
  #   restart: unless-stopped

# Uncomment if you're using a database volume
# volumes:
#   postgres_data:
