services:
  traefik:
    image: traefik:2.8
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik.service=api@internal"

  questionnaire:
    build: .
    container_name: questionnaire
    restart: always
    volumes:
      - ./db:/app/db
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - "${PORT}:${PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
      - "traefik.http.routers.questionnaire.tls=true"
      - "traefik.http.routers.questionnaire.rule=Host(`trainings.admin101.asuta.or.tz`)"
      - "traefik.http.routers.questionnaire.entrypoints=websecure"
      - "traefik.http.routers.questionnaire.tls.certresolver=letsencrypt"
      - "traefik.http.routers.questionnaire.service=questionnaire"
      - "traefik.http.services.questionnaire.loadbalancer.server.port=${PORT}"

networks:
  proxy:
    external: true